version: '3.5'
services:
  php-fpm:
    build: ./docker/php
    image: jefffrade/gran-backend:php-fpm
    restart: on-failure
    container_name: jefffrade-gran-backend-php-fpm
    command: php-fpm
    links:
      - mysql
    volumes:
      - ./:/gran-backend
    networks:
      - app
      - db
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 9000 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build: ./docker/nginx
    image: jefffrade/gran-backend:nginx
    restart: on-failure
    container_name: jefffrade-gran-backend-nginx
    command: nginx -g "daemon off;"
    links:
      - php-fpm
    ports:
      - "${DOCKER_NGINX_PORT_HTTP}:80"
    volumes:
      - ./:/gran-backend
    networks:
      - app
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 80 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  mysql:
    build: ./docker/mysql
    image: jefffrade/gran-backend:mysql
    restart: on-failure
    container_name: jefffrade-gran-backend-mysql
    volumes:
      - "${DOCKER_DATA_PATH}/mysql:/var/lib/mysql"
    command:
      - "--innodb_use_native_aio=0"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - db
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 3306 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

networks:
  app:
  db:
